#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := lcd_sd_card_fs_joypad_lv_lib_100ask

include $(IDF_PATH)/make/project.mk
